### ISSUE TITLE
TypeScript error

### ISSUE THREAD

**Issue by swaechterAS** [bitmovin/bitmovin-player-ui#250]
while running gulp i get a:

`Error: TypeScript error: src/ts/components/tvnoisecanvas.ts(100,7): Error TS2322: Type 'Timeout' is not assignable to type 'number'.`

VS code mark this line as well and says:
`
[ts] Type 'Timeout' is not assignable to type 'number'. [2322]
(property) TvNoiseCanvas.frameUpdateHandlerId: number
`

**Comment by stonko1994** [comment]
On which branch does this happen?

Can you check the installed typescript version with `npx tsc --version`

**Comment by protyposis** [comment]
This error usually happens in a Node envionment (Node uses type `Timeout` while in browsers it is a `number`). Do you import the UI into such an environment? 

This is usually fixed by setting the type to `any` (or maybe `unknown` in newer TS versions), and we might have to do that. It does not matter which type this is anyway because we never use the value directly.

**Comment by swaechterAS** [comment]
Typescript version is: Version 1.5.3

For now we use the assets included in the players package.

**Comment by protyposis** [comment]
> Typescript version is: Version 1.5.3

Are you absolutely sure? The UI is on TS 3 and I am pretty sure it would not compile with TS 1.5 or be compatible with type definitions generated by v3.



> For now we use the assets included in the players package.

What you you mean with "assets"?

**Comment by beersbr** [comment]
I am also having this issue. My `tsc` version is 3.6.3. I got past the issue by using your suggestion @protyposis. Since this is still in the master branch and still and issue and not getting more complaints I'm assuming I'm still doing something wrong. Is there a specific node version that I should be using?

**Comment by alexpcoleman** [comment]
As mentioned by @protyposis, I changed `private frameUpdateHandlerId: number;` to `private frameUpdateHandlerId: any;` in `tvnoisecanvas.ts`, which resolved this issue. Note that I have the repo within my main application's repo – guessing that's the cause somehow, because if I clone the repo outside of my app repo and build, it works fine out of the box.
