### ISSUE TITLE
index.html is broken, "TypeError: player.isAirplayAvailable is not a function", v7.0.5

### ISSUE THREAD

**Issue by ireneuszsawicki** [bitmovin/bitmovin-player-ui#3]
Hi there,

I've been trying to run index.html UI demo, but unfortunately I'm getting error "TypeError: player.isAirplayAvailable is not a function". See attached screenshot.

![screenshot_10](https://cloud.githubusercontent.com/assets/4947745/22241367/5485765c-e21f-11e6-946c-ab71e311b4f0.png)

Whenever I'm trying to switch anything using selectboxes below player, player goes black with another error "Uncaught TypeError: Cannot read property 'release' of undefined".

Chrome 55.0.2883.87 m.

Best,
Irek

**Comment by protyposis** [comment]
Hi Irek,

You get this error because AirPlay support is an upcoming feature in player 7.1 which is not released yet, but it's UI support is already in the dev branch. To solve the issue for now, you can try to comment out [this line](https://github.com/bitmovin/bitmovin-player-ui/blob/24c789c0ca5e9119c4a7c1e538d071b30f43836b/src/ts/uimanager.ts#L222) or better work with the [player-v7.0.5 tag](https://github.com/bitmovin/bitmovin-player-ui/tree/player-v7.0.5).

Cheers,
Mario

**Comment by ireneuszsawicki** [comment]
Hi Mario,

Got it. Thanks for the explanation. I've switched to v7.0.5 tag & everything seems to work fine.

Best,
Irek.
